const userInfo = {
    name: "Arild Maka",
    tlf: `917 57 159`,
    email: `arildb.kodehode@gmail.com`,
    pitch1: `Etter ca. 30 år i forsvaret startet jeg i 2022 min nye karriere som Frontend-utvikler. Dette fikk en kick-start gjennom et frontend utviklerkurs hos Jobloop.`,
    pitch2: `Har jobbet med data i Forsvaret i diverse stillinger fra tekniker til leder for dataavdelingen ved forsvarskommandoen i Stavanger frem til den ble lagt ned. De siste årene har jeg jobbet i Heimevernet.`,
    pitch3: `Fritiden er i stor grad brukt til judo og korpsmusikk. Har her hatt mange tillitsverv i tillegg til roller som trener og dommer.`,
    about1: `Jeg ble kjent med html allerede i 1995 og var da ansvarlig for flere nettsider for frivillige organisasjoner. Men disse sidene ble etterhvert overført til nyere plattformer og andre overtok publiseringen. Nå deltar jeg på et frontend utviklerkurs hos Jobloop for å oppdatere mine kunnskaper og bli en profesjonell Frontend-utvikler. Jeg har alltid drømt om å programmere og har nå endelig fått mulighet til å gå denne veien.`,
    about2: `Jeg har jobbet over 30 år i forsvaret. Har driftet det meste fra ND-stormaskiner til moderne servere, klienter og nettverk. Store deler av denne tiden var jeg leder for dataavdelingen på forsvarskommandoen i Stavanger. De siste årene har jeg jobbet i Heimevernet.`,
    about3: `Fritiden har i stor grad blitt brukt til korpsmusikk og judo. Har spilt klarinett i mange år og har etterhvert gått over til bassklarinett og kontrabassklarinett. Har trent judo siden 1983 og innehar nå svart belte av 5. grad. Er for tiden leder av judoklubben.`,
    about4: `For øvrig bor jeg i Stavanger, er single og uten barn. For tiden er jeg leder i boligsameiet der jeg bor. Opp gjennom årene har jeg hatt et utall verv både i styrer og komiteer i korpslivet og judoforbundet.`,
    about5: `Min filosofi er at det jeg lager skal bli bra. Dette inkluderer et godt språk og resultater som sluttbruker er fornøyd med. For meg er det viktig å kunne ha flere baller i luften samtidig og evne å prioritere ut fra hva som er viktig for det enkelte prosjekt.`,
    skill1: `HTML`,
    skill2: `CSS`,
    skill3: `Javascript`,
    skill4: `React`,
    skill5: `Phyton`,
    skill6: `IT drift`,
    skill7: `Ledelse`,
    project1: `Oppgave med "Parallax Website".`,
    project2: `Oppgave med severdigheter i Stavanger.`,
    project3: `Gruppeprosjekt høstferie 2022.`,
    project4: `Oppgave med mer avansert CSS.`,
    project5: `Juleprosjekt med nedtelling til jul og mulighet for å legge inn julehilsener.`,
    project6: `Quiz-app`,
}

export default userInfo